### ISSUE TITLE
_manifest.scss references non-existent utils/_eggbox

### ISSUE THREAD

**Issue by danmur** [hatchddigital/empty-coop#15]

**Comment by shadowmint** [comment]
https://github.com/hatchddigital/empty-coop/blob/master/gulp/tasks/fonts.js#L61 *should* create this file... I'll look into why this isn't working.

Note that you have to run the fonts task *before* the styles task for this to work...

**Comment by shadowmint** [comment]
Should be fixed in https://github.com/hatchddigital/empty-coop/commit/da5bb53e575a4d04ebb06f2d825a1d675894510e
