### ISSUE TITLE
Should eggbox font files and eggbox.less not be in git ignore ?

### ISSUE THREAD

**Issue by neilferreira** [hatchddigital/empty-coop#9]
When running grunt server you're left with a few untracked files, static/fonts/eggbox/* and eggbox.less

Should these be in git ignore? Keeping in mind that someone should be able to download empty coop and fire it up 'as is' without running Grunt.

**Comment by jackarmley** [comment]
Closing this, as eggbox is now in sass, and fonts/eggbox are ignored before compile time.

**Comment by humaan** [comment]
![ohrxxmp](https://cloud.githubusercontent.com/assets/1941007/8248804/ba9fd66e-1695-11e5-911c-b182e422b0e9.jpg)

**Comment by niaal** [comment]
Ignore me dudes, came to unsubscribe and post a hilarious meme. Ended up using the work account.

Enjoy your day.
